import React from 'react';

const Loader = () => {
    return (
        <div>
            LOADING....
            LOADING....
            LOADING....
            LOADING....
            LOADING....
            LOADING....
            LOADING....
            LOADING....
            LOADING....
            LOADING....
        </div>
    );
};

export default Loader;